# site settings
title: Sys Creativity
subtitle: by the Institute for Systematizing Creativity
email: systematizingcreativity@gmail.com
description: Revel in the Moment of Creation.
baseurl: # the subpath of your site, e.g. /blog — works if removed 
url: # the base hostname & protocol for your site — works if removed
author:
# street_address: 450 Pepper Ave.
# city: Palo Alto
# state: CA
# zip_code: 94306
# country: United States of America

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown
# remote_theme: christopherii/forty-jekyll-theme

sass:
  style: compressed
